### ISSUE TITLE
Add  !default for scss variables

### ISSUE THREAD

**Issue by tyllo** [SancheZz/vue-mask-number#2]
https://github.com/SancheZz/vue-mask-number/blob/4597721f4b58a9f65b314cd24aafc38cd2355aa0/VueMaskNumber/defaults.scss#L1

**Comment by SancheZz** [comment]
Thank you!
It has been [fixed](https://github.com/SancheZz/vue-mask-number/commit/a80293075a8e7ea9d20c2b7e904da7634f3e4d77)
