### ISSUE TITLE
 Module '"@yasanchezz/vue-mask-number"' has no exported member 'MaskNumberRef'

### ISSUE THREAD

**Issue by kTelyakov** [SancheZz/vue-mask-number#3]
Hi @SancheZz ! Im trying to use your cool input mask, but got some types error -  

```import type { MaskNumberRef } from '@yasanchezz/vue-mask-number'```

 Module '"@yasanchezz/vue-mask-number"' has no exported member 'MaskNumberRef'. Did you mean to use 'import MaskNumberRef from "@yasanchezz/vue-mask-number"' instead?

Do you change a some type definitions ? 

P.S.
thank you!

**Comment by SancheZz** [comment]
Hello @kTelyakov . All types are included to the package. Can you attach a reproduce link?

**Comment by kTelyakov** [comment]
I upgraded your package to latest version, and now all working correct, thank you @SancheZz  !
